.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GLADE-2 1 "24 January 2005"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
glade-2 \- GUI Builder for GTK+ 2
.SH SYNOPSIS
.B glade-2
.RI [ options ] " file"
.br
.SH DESCRIPTION
.B Glade
allows a graphical interface to be designed from within a graphical
interface, instead of written as a program using a function or class
library.
.PP
The creation of various GTK graphical "widgets" is supported, allowing
a programmer to concentrate on implementation of an applications
functionality, instead of the presentation.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP
.B \-w, \-\-write-source
Write the "source" code output files defined by the XML input file
.TP
.B \-\-hide-palette
Start with the palette hidden (only available with Gnome support)
.TP
.B \-\-hide-property-editor
Start with the property editor hidden (only available with Gnome support)
.TP
.B \-\-show-widget-tree
Start with the widget tree shown (only available with Gnome support)
.TP
.B \-\-show-clipboard
Start with the clipboard shown (only available with Gnome support)
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH FILES
A single input XML file may be given as an argument.  This file should
have been previous created by an interactive session with \fBGlade\fP.
.SH AUTHOR
glade-2 was written by Damon Chaplin.
.PP
This manual page was written by Justin Pryzby
<justinpryzby@users.sf.net>, for the Debian project (but may be used
by others).
